version: '3.7'
services:
  frontend_service:
    image: yyasin/frontend_service_image:latest
    deploy:
      replicas: 1
    ports:
    - target: 5000
      published: 5000
    
  location_service:
    image: yyasin/location_service_image:latest
    deploy:
      replicas: 1

  weather_service:
    image: yyasin/weather_service_image:latest
    deploy:
      replicas: 1

  movie_service:
    image: yyasin/movie_service_image:latest
    deploy:
      replicas: 1
    

