pipeline{
    agent any
    environment{
        VERSION = "1.${BUILD_ID}"
        AUTHOR = credentials("AUTHOR")
        SECRET_KEY = credentials("SECRET_KEY")
    }
    stages{
        stage("Build and Push Images"){
            steps{
                sh "bash jenkins/build_images.sh"
            }
        }
        stage("Deploy"){
            steps{
                sh "bash jenkins/deploy_compose.sh"
            }
        }
    }
}