pipeline{
    agent any
    environment{
        SECRET_KEY = credentials("SECRET_KEY")
    }
    stages{
        stage("Build and Push Images"){
            steps{
                sh "bash jenkins/build_images.sh"
            }

        stage("Configure Swarm"){
            steps{
                sh "/home/jenkins/.local/bin/ansible-playbook -i inventory playbook.yaml"
            }
        }
        stage("Deploy application"){
            steps{
                sh "bash jenkins/deploy_stack.sh"
            }
        }
    }
}