- name: Install all required system packages
  apt: 
    name={{ item }} 
    state=latest 
    update_cache=yes
  loop: 
    - python3
    - python3-pip
    - python-setuptools      
    - apt-transport-https 
    - ca-certificates
    - curl
    - software-properties-common 
    - virtualenv

- name: 'Docker’s official GPG key'
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker

- name: Add Docker Packages to Repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
  tags: docker

- name: Install docker
  apt: 
    name={{ item }} 
    state=latest 
    update_cache=yes
  loop: 
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Start docker service
  service:
    name: docker
    state: started

- name: pip install docker
  pip:
    name: docker